plants:
  grass:
    weight: 1.0
    maxPerCell: 200

animals:
  wolf:
    weight: 50.0
    maxPerCell: 30
    speed: 3
    maxFood: 8.0

  boa:
    weight: 15.0
    maxPerCell: 30
    speed: 1
    maxFood: 3.0

  fox:
    weight: 8.0
    maxPerCell: 30
    speed: 2
    maxFood: 2.0

  bear:
    weight: 500.0
    maxPerCell: 5
    speed: 2
    maxFood: 80.0

  eagle:
    weight: 6.0
    maxPerCell: 20
    speed: 3
    maxFood: 1.0

  horse:
    weight: 400.0
    maxPerCell: 20
    speed: 4
    maxFood: 60.0

  deer:
    weight: 300.0
    maxPerCell: 20
    speed: 4
    maxFood: 50.0

  rabbit:
    weight: 2.0
    maxPerCell: 150
    speed: 2
    maxFood: 0.45

  mouse:
    weight: 0.05
    maxPerCell: 500
    speed: 1
    maxFood: 0.01

  goat:
    weight: 60.0
    maxPerCell: 140
    speed: 3
    maxFood: 10.0

  sheep:
    weight: 70.0
    maxPerCell: 140
    speed: 3
    maxFood: 15.0

  boar:
    weight: 400.0
    maxPerCell: 50
    speed: 2
    maxFood: 50.0

  buffalo:
    weight: 700.0
    maxPerCell: 10
    speed: 3
    maxFood: 100.0

  duck:
    weight: 1.0
    maxPerCell: 200
    speed: 4
    maxFood: 0.15

  caterpillar:
    weight: 0.01
    maxPerCell: 1000
    speed: 0
    maxFood: 0.0

food:
  WOLF:
    HORSE: 10
    DEER: 15
    RABBIT: 60
    MOUSE: 80
    GOAT: 60
    SHEEP: 70
    BOAR: 15
    BUFFALO: 10
    DUCK: 40

  BOA:
    FOX: 15
    RABBIT: 20
    MOUSE: 40
    DUCK: 10

  FOX:
    RABBIT: 70
    MOUSE: 90
    DUCK: 60
    CATERPILLAR: 40

  BEAR:
    BOA: 80
    HORSE: 40
    DEER: 80
    RABBIT: 80
    MOUSE: 90
    GOAT: 70
    SHEEP: 70
    BOAR: 50
    BUFFALO: 20
    DUCK: 10

  EAGLE:
    FOX: 10
    RABBIT: 90
    MOUSE: 90
    DUCK: 80

  HORSE:
    PLANT: 100

  DEER:
    PLANT: 100

  RABBIT:
    PLANT: 100

  MOUSE:
    CATERPILLAR: 90
    PLANT: 100

  GOAT:
    PLANT: 100

  SHEEP:
    PLANT: 100

  BOAR:
    MOUSE: 50
    CATERPILLAR: 90
    PLANT: 100

  BUFFALO:
    PLANT: 100

  DUCK:
    CATERPILLAR: 90
    PLANT: 100

  CATERPILLAR:
    PLANT: 100

plantGrowthPerStep: 2
reproductionChance: 20
starvationRate: 0.1